/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sheet;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author akhrain
 */
public class EditFileFrame extends javax.swing.JFrame 
{
    int fontSize = SheetFrame.editorFontSize;
    SheetFile  sfile  = null;
    SheetFrame sframe = null;

    /**
     * Creates new form EditFileFrame
     */
    public EditFileFrame(SheetFile sf, SheetFrame sfr) 
    {
        sfile  = sf;
        sframe = sfr;
        setTitle("Edit File");
        initComponents();
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent ev) 
                {
                    exit();
                }
            });
    }
    
    public void setAttributes()
    {
        fontSize = 10;
        labelFile.setText(sfile.getName());
        labelPath.setText(sfile.getFile().getAbsolutePath());
        setFont();
        txtArea.setBackground(Color.black);
        txtArea.setForeground(Color.white);
        txtArea.setCaretColor(Color.white);
        txtArea.setText(sfile.getText());
        txtArea.setCaretPosition(0);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelFile = new javax.swing.JLabel();
        labelPath = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnEnlargeFont = new javax.swing.JButton();
        btnReduceFont = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("FILE:");

        jLabel2.setText("PATH:");

        labelFile.setText("-");

        labelPath.setText("-");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnEnlargeFont.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        btnEnlargeFont.setText("+");
        btnEnlargeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlargeFontActionPerformed(evt);
            }
        });

        btnReduceFont.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        btnReduceFont.setText("-");
        btnReduceFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReduceFontActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPath, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnlargeFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReduceFont, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelPath))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnlargeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReduceFont, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String[] options = {"Save and update", "Only save", "Cancel"};
        String message =  "Do you want to save the file:\n"
                         + sfile.getFile().getAbsolutePath() + "\n"
                         + "and/or update your CodeSheet?";
        int i = JOptionPane.showOptionDialog(this, message, "Save", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(i == 0) 
        {
            try{ sfile.overwrite(txtArea.getText()); }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(this, "ERROR WRITING THE FILE: "+e.getMessage(), "ERROR WRITING THE FILE", JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }
            sframe.updateCodeSheet();
//            this.dispose();
            return;
        }
        else if(i == 1)
        {
            try{ sfile.overwrite(txtArea.getText()); }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(this, "ERROR WRITING THE FILE: "+e.getMessage(), "ERROR WRITING THE FILE", JOptionPane.ERROR_MESSAGE);
            }
//            this.dispose();
            return;
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        exit();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEnlargeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlargeFontActionPerformed
        increaseFont();
        setFont();
    }//GEN-LAST:event_btnEnlargeFontActionPerformed

    private void btnReduceFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReduceFontActionPerformed
        decreaseFont();
        setFont();
    }//GEN-LAST:event_btnReduceFontActionPerformed

    public void setFont()
    {
        txtArea.setFont(new Font(Font.MONOSPACED, Font.PLAIN , fontSize));
    }
    
    public void increaseFont()
    {
        if(fontSize >= 80) return;
        fontSize++;
    }
    
    public void decreaseFont()
    {
        if(fontSize <= 5) return;
        fontSize--;
    }
    
    public void exit()
    {
        int i = JOptionPane.showConfirmDialog(this, "Do you want to close this window? (if you did not saved your changes, you will lose them)", "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(i == 0) this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEnlargeFont;
    private javax.swing.JButton btnReduceFont;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFile;
    private javax.swing.JLabel labelPath;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
