/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sheet;

/**
 *
 * @author akhrain
 */
public class ModifyNumVariableDialog extends javax.swing.JDialog {

    private String var       = null;
    private SheetFrame sf    = null;
    
    /**
     * Creates new form ModifyNumVariableDialog
     */
    public ModifyNumVariableDialog(java.awt.Frame parent, boolean modal, String v) 
    {
        super(parent, modal);
        var = v;
        sf  = (SheetFrame)parent;
        setTitle(v);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldEqual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEqual = new javax.swing.JButton();
        btnPlusEqual = new javax.swing.JButton();
        txtFieldPlusEqual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFieldEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEqualActionPerformed(evt);
            }
        });

        jLabel1.setText("=");

        jLabel2.setText("+=");

        btnEqual.setText(">");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnPlusEqual.setText(">");
        btnPlusEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusEqualActionPerformed(evt);
            }
        });

        txtFieldPlusEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPlusEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEqual))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldPlusEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlusEqual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnPlusEqual)
                    .addComponent(txtFieldPlusEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnEqual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEqualActionPerformed
        changeValue();
    }//GEN-LAST:event_txtFieldEqualActionPerformed

    private void txtFieldPlusEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPlusEqualActionPerformed
        addValue();
    }//GEN-LAST:event_txtFieldPlusEqualActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        changeValue();
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnPlusEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusEqualActionPerformed
        addValue();
    }//GEN-LAST:event_btnPlusEqualActionPerformed

    private void changeValue()
    {
        Double d = (new Line(null, txtFieldEqual.getText(), sf.getCodeSheet())).solve(sf.getCodeSheet(), sf.getRootMacro());
        if(d != null) sf.getRootMacro().setVariable(var, d.doubleValue());
        this.dispose();
    }
    
    private void addValue()
    {
        Double d = (new Line(null, txtFieldPlusEqual.getText(), sf.getCodeSheet())).solve(sf.getCodeSheet(), sf.getRootMacro());
        Double v = sf.getRootMacro().getVariable(var);
        if(d != null && v != null) sf.getRootMacro().setVariable(var, d.doubleValue()+v.doubleValue());
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnPlusEqual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFieldEqual;
    private javax.swing.JTextField txtFieldPlusEqual;
    // End of variables declaration//GEN-END:variables
}
