/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sheet;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author akhrain
 */
public class NewFileFrame extends javax.swing.JFrame 
{
    int fontSize = SheetFrame.editorFontSize;
    SheetFile  sfParent  = null;
    SheetFrame sframe    = null;
    String name = null;
    int fileType = -1;

    /**
     * Creates new form EditFileFrame
     */
    public NewFileFrame(SheetFile sfp, int type,SheetFrame sfr) 
    {
        initComponents();
        sfParent = sfp;
        sframe   = sfr;
        fileType = type;
        setTitle("New File");
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent ev) 
                {
                    exit();
                }
            });
        setAttributes();
    }
    
    public void setAttributes()
    {
        fontSize = 10;
        if(sfParent != null)
        {
            if(sfParent.getFile() != null)
                labelDirectoryPath.setText(sfParent.getFile().getAbsolutePath());
        }
        else labelDirectoryPath.setText(sframe.getCodeSheet().getRootFolder().getAbsolutePath());
        if(fileType == SheetFile.CSHEET) labelTitle.setText("CREATING A NEW CSHEET FILE ");
        else if (fileType == SheetFile.CTABLE) labelTitle.setText("CREATING A NEW CTABLE FILE");
        setFont();
        txtArea.setBackground(Color.black);
        txtArea.setForeground(Color.white);
        txtArea.setCaretColor(Color.white);
        txtArea.setCaretPosition(0);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelDirectoryPath = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        labelTitle = new javax.swing.JLabel();
        btnEnlargeFont = new javax.swing.JButton();
        btnReduceFont = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("DIRECTORY PATH:");

        labelDirectoryPath.setText("-");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        labelTitle.setText("-");

        btnEnlargeFont.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        btnEnlargeFont.setText("+");
        btnEnlargeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnlargeFontActionPerformed(evt);
            }
        });

        btnReduceFont.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        btnReduceFont.setText("-");
        btnReduceFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReduceFontActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(labelDirectoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnlargeFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReduceFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnlargeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelDirectoryPath)
                    .addComponent(btnReduceFont, javax.swing.GroupLayout.PREFERRED_SIZE, 14, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Do you want to create the file?", "Create File", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (i == 0) 
            sframe.newFile(txtArea.getText(),fileType,sfParent);
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        exit();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEnlargeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnlargeFontActionPerformed
        increaseFont();
        setFont();
    }//GEN-LAST:event_btnEnlargeFontActionPerformed

    private void btnReduceFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReduceFontActionPerformed
        decreaseFont();
        setFont();
    }//GEN-LAST:event_btnReduceFontActionPerformed

    public void setFont()
    {
        txtArea.setFont(new Font(Font.MONOSPACED, Font.PLAIN , fontSize));
    }
    
    public void increaseFont()
    {
        if(fontSize >= 80) return;
        fontSize++;
    }
    
    public void decreaseFont()
    {
        if(fontSize <= 5) return;
        fontSize--;
    }

    public void exit()
    {
        int i = JOptionPane.showConfirmDialog(this, "Do you want to close this window without saving changes?", "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (i == 0) this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEnlargeFont;
    private javax.swing.JButton btnReduceFont;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDirectoryPath;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
